// <auto-generated />
using EmployeeGRPC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeGRPC.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20230919091157_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeGRPC.Models.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeList");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "makarapura",
                            Email = "abc@gmail.com",
                            Name = "Abc"
                        },
                        new
                        {
                            Id = 2L,
                            Address = "bustand",
                            Email = "xyz@gmail.com",
                            Name = "xyz"
                        },
                        new
                        {
                            Id = 3L,
                            Address = "changa",
                            Email = "ram@gmail.com",
                            Name = "ram"
                        },
                        new
                        {
                            Id = 4L,
                            Address = "changa",
                            Email = "shyam@gmail.com",
                            Name = "shyam"
                        },
                        new
                        {
                            Id = 5L,
                            Address = "Testpura",
                            Email = "test@gmail.com",
                            Name = "Test"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
